services:
  web:
    build: .
    ports:
      - "5050:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/contactos_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: contactos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
